services:
  - name: fastapi-web
    type: web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        fromService:
          name: product-db
          type: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: product-redis
          type: redis
          property: connectionString

  - name: celery-worker
    type: worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A app.celery_app.celery worker --loglevel=info --pool=solo"
    envVars:
      - key: DATABASE_URL
        fromService:
          name: product-db
          type: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: product-redis
          type: redis
          property: connectionString

databases:
  - name: product-db
    plan: free

redis:
  - name: product-redis
    plan: free
